### ISSUE TITLE
One to Many Mapping on Axis

### ISSUE THREAD

**Issue by mohithingorani** [syntagmatic/parallel-coordinates#314] opened 2016-07-04 21:38 UTC
In my dataset there are a few one to many possible mappings.
For example Value A on Axis 1 is mapped to Value B, C,E on Axis 2.

What should i do in such a scenario?
Thanks!

**Comment by syntagmatic** [comment] 2016-07-04 22:01
Duplicate of #304 
The only way to model it currently is to have an extra row of data each for B, C and E. Multiple attributes per axis are not supported.

**Closed by syntagmatic** 2016-07-04 22:01 UTC
